apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: ${containerRegistry}/${imageRepository}:product-${tag}
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5001
        imagePullPolicy: Always
      imagePullSecrets:
      - name: ${imagePullSecret}
---
apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: product
  ports:
  - port: 80
    targetPort: 5001
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-ingress
spec:
  rules:
  - host: "product.akinisik.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: product-svc
            port:
              number: 80