FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /app
COPY . .
RUN dotnet restore "/app/IdentityServerSample/IdentityServerSample.csproj"
RUN dotnet build "/app/IdentityServerSample/IdentityServerSample.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "/app/IdentityServerSample/IdentityServerSample.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "/app/IdentityServerSample.dll"]