FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /app
COPY . .
RUN dotnet restore "/app/ProductService/ProductService.csproj"
RUN dotnet build "/app/ProductService/ProductService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "/app/ProductService/ProductService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "/app/ProductService.dll"]